### ISSUE TITLE
set_option is not implemented for IvfMuxer

### ISSUE THREAD

**Issue by shssoichiro** [rust-av/ivf-rs#12]
Theoretically it should be able to set any of the properties on IvfMuxer (except info). Although this might just be a secondary interface when there's no GlobalInfo struct available.

**Comment by Luni-4** [comment]
Can we include this one in 0.4 @shssoichiro? It doesn't seem complicated

**Comment by shssoichiro** [comment]
Kind of forgot it existed 😅  Yep, I agree.
